# Generated by Django 4.0.5 on 2022-08-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_test_questions_question_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='Course',
        ),
    ]
