# Generated by Django 4.0.5 on 2022-08-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_rename_questions_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Course',
            new_name='questions',
        ),
    ]
